services:
  postgres:
    image: postgres:15-alpine
    container_name: sagri_hrm_postgres
    restart: always
    ports:
      # Cổng 5432 trên máy đã bị PostgreSQL native chiếm -> map ra 5433
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sagri@2026
      POSTGRES_DB: sagri_hrm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
