import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // All colors point to CSS variables → theme-aware at runtime
        "primary":                      "var(--primary)",
        "primary-fixed":                "var(--primary-fixed)",
        "primary-fixed-dim":            "var(--primary-fixed)",
        "on-primary":                   "var(--on-primary)",
        "on-primary-fixed":             "var(--on-primary-container)",
        "on-primary-fixed-variant":     "var(--on-primary)",
        "primary-container":            "var(--primary-container)",
        "on-primary-container":         "var(--on-primary-container)",

        "secondary":                    "var(--secondary)",
        "secondary-fixed":              "var(--primary-fixed)",
        "secondary-fixed-dim":          "var(--secondary)",
        "on-secondary":                 "var(--on-secondary)",
        "on-secondary-fixed":           "var(--on-secondary-container)",
        "on-secondary-fixed-variant":   "var(--on-secondary)",
        "secondary-container":          "var(--secondary-container)",
        "on-secondary-container":       "var(--on-secondary-container)",

        "tertiary":                     "var(--tertiary)",
        "tertiary-fixed":               "var(--tertiary-container)",
        "tertiary-fixed-dim":           "var(--tertiary)",
        "on-tertiary":                  "var(--on-tertiary)",
        "on-tertiary-fixed":            "var(--on-tertiary-container)",
        "on-tertiary-fixed-variant":    "var(--on-tertiary)",
        "tertiary-container":           "var(--tertiary-container)",
        "on-tertiary-container":        "var(--on-tertiary-container)",

        "error":                        "var(--error)",
        "on-error":                     "var(--on-error)",
        "error-container":              "var(--error-container)",
        "on-error-container":           "var(--on-error-container)",

        "background":                   "var(--background)",
        "on-background":                "var(--on-background)",
        "surface":                      "var(--surface)",
        "surface-dim":                  "var(--surface-dim)",
        "surface-bright":               "var(--surface-bright)",
        "on-surface":                   "var(--on-surface)",
        "on-surface-variant":           "var(--on-surface-variant)",

        "surface-container-lowest":     "var(--surface-container-lowest)",
        "surface-container-low":        "var(--surface-container-low)",
        "surface-container":            "var(--surface-container)",
        "surface-container-high":       "var(--surface-container-high)",
        "surface-container-highest":    "var(--surface-container-highest)",
        "status-success":               "var(--status-success)",

        "outline":                      "var(--outline)",
        "outline-variant":              "var(--outline-variant)",
        "inverse-surface":              "var(--inverse-surface)",
        "inverse-on-surface":           "var(--inverse-on-surface)",
        "inverse-primary":              "var(--inverse-primary)",
        "surface-tint":                 "var(--surface-tint)",
      },
      spacing: {
        "sm":              "8px",
        "base":            "4px",
        "lg":              "24px",
        "xs":              "4px",
        "gutter":          "16px",
        "margin-mobile":   "16px",
        "xl":              "32px",
        "md":              "16px",
        "margin-desktop":  "32px"
      },
      fontFamily: {
        "display-lg":         ["Geist", "sans-serif"],
        "label-caps":         ["JetBrains Mono", "monospace"],
        "body-sm":            ["Hanken Grotesk", "sans-serif"],
        "headline-md":        ["Geist", "sans-serif"],
        "body-md":            ["Geist", "sans-serif"],
        "display-lg-mobile":  ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg":            ["Geist", "sans-serif"],
        "label-md":           ["Geist", "sans-serif"],
        "label-sm":           ["Geist", "sans-serif"],
        "headline-lg":        ["Geist", "sans-serif"],
      },
      fontSize: {
        "display-lg":         ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps":         ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm":            ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md":        ["20px", { lineHeight: "1.3",  fontWeight: "600" }],
        "body-md":            ["14px", { lineHeight: "1.5",  fontWeight: "400" }],
        "display-lg-mobile":  ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2",  fontWeight: "600" }],
        "body-lg":            ["16px", { lineHeight: "1.5",  fontWeight: "400" }],
        "label-md":           ["12px", { lineHeight: "1",    letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm":           ["11px", { lineHeight: "1",    fontWeight: "600" }],
        "headline-lg":        ["32px", { lineHeight: "1.2",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm":        ["20px", { lineHeight: "1.3",  fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
